🚧 [In progress] Azure tests and Deployment
equinor/oneseismic pull request #528
Opened 2022-03-02 20:01 UTC by achaikou

Creating a PR, still need to fix a few things, but firstly want to make the job running

2022-04-12 15:07 UTC, sveinung-r requested changes

2022-04-12 15:07 UTC, sveinung-r commented on deploy/create/create.sh
> +# (Data of service principle who is allowed to create resources in RESOURCE_GROUP)
Service principal

2022-04-12 15:07 UTC, sveinung-r commented on deploy/update/update.sh
> +# (Data of service principle who is allowed to create resources in RESOURCE_GROUP)
Service principal

2022-04-19 19:21 UTC, achaikou commented
Can't combine bicep files under same main, at least for now: for correct work between "create" and "update" phase nginx image must be supplied, so these really are two stages.

2022-04-26 12:48 UTC, sveinung-r approved these changes

2022-04-26 17:42 UTC, merged